// Extended help for the wizard fields, written for users who have never
// worked with SCOS-2000 / CCS5 / PUS before. Paraphrased from the SCOS-2000
// Database Import ICD (EGOS-MCS-S2K-ICD-0001 issue 7.0) and ECSS-E-ST-70-41.

export interface HelpTopic {
  title: string
  body: string[]
  example?: string
  ref?: string
}

const APID: HelpTopic = {
  title: 'APID — Application Process ID',
  body: [
    'Every CCSDS space packet carries an 11-bit APID (0–2047) in its primary '
    + 'header. It identifies the on-board application that produced (TM) or '
    + 'consumes (TC) the packet — think of it as the address of your unit on '
    + 'the spacecraft.',
    'APIDs are allocated by the system/prime contractor — you do not invent '
    + 'one, you use the value assigned to your unit. Most units use the same '
    + 'APID for their telemetry and their commands; some missions assign '
    + 'separate TM and TC APIDs.',
    'If the APID is wrong, the ground simply never matches your packets — '
    + 'everything else can be perfect and you will still see nothing decode.',
  ],
  example: 'Your unit was allocated APID 100. All its HK packets carry APID '
    + '100, and commands to it are routed using APID 100.',
  ref: 'CCSDS 133.0-B / PUS; MIB fields PID_APID and CCF_APID (ICD §3.3.2.4.1, §3.3.3.2.1).',
}

export const packetHelp: Record<string, HelpTopic> = {
  service: {
    title: 'PUS service of the packet',
    body: [
      'The Packet Utilisation Standard (PUS) gives every packet a service '
      + 'type and subtype that say what the packet *means*. The ground uses '
      + 'them (together with the APID) to identify the packet.',
      'For a typical unit you will mostly create:\n'
      + '• (3,25) housekeeping parameter report — your periodic HK; one '
      + 'packet definition per SID\n'
      + '• (5,1)…(5,4) event reports — anomalies and notable events, by '
      + 'increasing severity\n'
      + '• (17,2) are-you-alive reply — the answer to a (17,1) connection test',
      'Service-1 reports (command verification) are normally generated by '
      + 'the platform software, not defined by unit teams.',
      'Selecting a service here only pre-fills the type/subtype numbers — '
      + 'you can always edit them for mission-specific services.',
    ],
    ref: 'ECSS-E-ST-70-41 (PUS); see also the in-app "MIB & PUS guide" page.',
  },
  typestype: {
    title: 'Service type / subtype',
    body: [
      'These two numbers are carried in the PUS secondary header of every '
      + 'packet. Together with the APID (and the SID, if used) they tell the '
      + 'ground which packet definition applies.',
      'They become PID_TYPE and PID_STYPE in the MIB. Two packet definitions '
      + 'may share the same type/subtype/APID only if they are distinguished '
      + 'by an additional identification value (PI1, e.g. the SID).',
    ],
    example: 'A housekeeping report is type 3, subtype 25 — written as (3,25).',
    ref: 'ICD §3.3.2.4.1 (pid).',
  },
  apid: APID,
  descr: {
    title: 'Packet description',
    body: [
      'Free text (max 64 characters) shown in ground displays and packet '
      + 'lists. Write it for the operator on console: name the unit and what '
      + 'the packet contains.',
      'Stored as PID_DESCR.',
    ],
    example: '"XYZ standard housekeeping" or "XYZ event report (high severity)".',
  },
  mnemonic: {
    title: 'Packet mnemonic',
    body: [
      'A short name (max 12 characters) used in compact ground displays, '
      + 'stored in the packet characteristics table (TPCF_NAME).',
      'Optional but recommended — many tools show this instead of the long '
      + 'description. A common convention is <UNIT>_<KIND><n>.',
    ],
    example: 'XYZ_HK1, XYZ_EVH',
  },
  sid: {
    title: 'SID — Structure ID (PI1 value)',
    body: [
      'All housekeeping reports share the same APID and type/subtype (3,25), '
      + 'so the ground needs one more value to tell them apart: the Structure '
      + 'ID (SID), carried as the first field of the packet body.',
      'Enter the SID value of *this* packet here (it becomes PID_PI1_VAL), '
      + 'and mark the field that carries it in the parameter list below ("ID '
      + 'field"). The wizard then writes a PIC record telling the ground at '
      + 'which byte offset and width to read the SID for all (3,25) packets.',
      'Leave it empty for packets that are unique by APID + type/subtype '
      + 'alone (e.g. a single (17,2) reply).',
    ],
    example: 'Your unit has two HK reports: SID 1 (standard, 8 s) and SID 2 '
      + '(diagnostic, 1 s) — two packet definitions, same APID and (3,25).',
    ref: 'ICD §3.3.2.4.1 (PID_PI1_VAL) and §3.3.2.4.2 (pic).',
  },
  dfh: {
    title: 'Data field header size',
    body: [
      'Between the 6-byte CCSDS primary header and your actual data, every '
      + 'PUS packet carries a secondary header (the "data field header"): PUS '
      + 'version, service type/subtype, usually the generation time stamp, '
      + 'and possibly spare/padding bytes.',
      'For telemetry the MIB does not describe this header field by field — '
      + 'it only needs its total size in bytes (PID_DFHSIZE) so the ground '
      + 'knows where your data starts. The wizard places your first parameter '
      + 'at byte 6 + this size.',
      'The value is mission-specific — take it from your space-to-ground '
      + 'ICD. Common values are 10–16 bytes (e.g. 3 bytes PUS header + 6–7 '
      + 'bytes CUC/CDS time + padding).',
      'If this number is wrong, every parameter in the packet is shifted and '
      + 'decodes as garbage — it is the first thing to check when decoded '
      + 'values look wrong.',
    ],
    ref: 'ICD §3.3.2.4.1 (PID_DFHSIZE).',
  },
  time: {
    title: 'Time stamp in the header',
    body: [
      'Whether the data field header of this packet contains the on-board '
      + 'generation time (PID_TIME = Y/N). Standard PUS TM packets do.',
      'When present, the ground extracts it, applies the mission time '
      + 'correlation, and archives all parameter samples with that time. '
      + 'The time format itself (CUC/CDS variant) is mission configuration, '
      + 'not part of this packet definition.',
    ],
    ref: 'ICD §3.3.2.4.1 (PID_TIME).',
  },
  pec: {
    title: 'Packet Error Control (CRC)',
    body: [
      'Standard PUS packets end with a 2-byte CRC checksum, the Packet Error '
      + 'Control. The wizard only uses this to compute the total packet size '
      + 'stored in tpcf — do not list the CRC as a parameter.',
      'Whether the ground *verifies* the CRC on reception is a separate '
      + 'setting (PID_CHECK in the pid table, default off).',
    ],
    ref: 'ICD §3.3.2.4.1 (PID_CHECK), §3.3.2.4.3 (TPCF_SIZE).',
  },
  interval: {
    title: 'Generation interval',
    body: [
      'For periodic packets: how often the unit nominally sends it, in '
      + 'milliseconds (PID_INTER).',
      'The ground uses this to detect staleness: if a periodic packet stops '
      + 'arriving, all parameters contained in it are flagged as "expired" '
      + 'after this interval plus a configurable margin — so an operator '
      + 'immediately sees that values are no longer fresh.',
      'Leave it empty for event-driven (sporadic) packets.',
    ],
    example: 'Housekeeping every 8 seconds → 8000.',
    ref: 'ICD §3.3.2.4.1 (PID_INTER).',
  },
  params: {
    title: 'Parameters in the packet body',
    body: [
      'List every field of the packet body in its exact on-board order, '
      + 'starting right after the data field header. Each row becomes:\n'
      + '• a TM parameter definition (pcf) — created automatically if the '
      + 'name is new, reused if it exists\n'
      + '• a location entry (plf) — the byte/bit position in this packet, '
      + 'computed from the field widths',
      'The width of each field comes from its type (PTC) and format (PFC) — '
      + 'e.g. PTC 3 / PFC 12 is a 16-bit unsigned integer. Use the type '
      + 'picker if you do not know the codes.',
      'Use the arrows to reorder; the packet map below updates live so you '
      + 'can cross-check offsets against your unit’s ICD. For housekeeping '
      + 'packets the first field is usually the 16-bit SID — mark it as the '
      + 'ID field.',
      'Note: this wizard covers fixed-layout packets (every field at a '
      + 'constant position). Packets with repeating groups or variable '
      + 'structure are defined in the vpd table instead.',
    ],
    ref: 'ICD §3.3.2.1.1 (pcf), §3.3.2.5.1 (plf), Appendix A (PTC/PFC).',
  },
}

export const commandHelp: Record<string, HelpTopic> = {
  cname: {
    title: 'Command name',
    body: [
      'The unique mnemonic of the command (max 8 characters, CCF_CNAME). It '
      + 'appears in command stacks, logs and reports — operators will type '
      + 'and read it constantly.',
      'Many projects prescribe a naming convention (e.g. unit prefix + '
      + 'function); check yours before inventing names. Uppercase letters '
      + 'and digits are the safe choice.',
    ],
    example: 'XYZMODE — "set mode of unit XYZ".',
    ref: 'ICD §3.3.3.2.1 (ccf).',
  },
  descr: {
    title: 'Command description',
    body: [
      'Short free text (max 24 characters, CCF_DESCR) shown next to the '
      + 'command name in stacks and histories. A longer detailed description '
      + 'can be added later in the ccf table (CCF_DESCR2, 64 characters).',
    ],
  },
  service: {
    title: 'PUS service of the command',
    body: [
      'Most unit-specific commands are (8,1) "perform function": a generic '
      + 'envelope meaning "execute function X with these arguments". The '
      + 'first argument is then a fixed Function ID that your on-board '
      + 'software uses to dispatch — the wizard has a button to add it.',
      'Other services you may need:\n'
      + '• (3,5)/(3,6) enable/disable housekeeping reports\n'
      + '• (17,1) are-you-alive test — implement early, it is the simplest '
      + 'end-to-end check\n'
      + '• (20,1)/(20,3) read/set on-board parameters by ID',
      'The selection only pre-fills the type/subtype; edit them freely for '
      + 'mission-specific services.',
    ],
    ref: 'ECSS-E-ST-70-41 (PUS), service 8.',
  },
  typestype: {
    title: 'Service type / subtype',
    body: [
      'Written into the PUS header of the command packet (CCF_TYPE / '
      + 'CCF_STYPE) by the packet header definition. Together with the APID '
      + 'they tell the on-board software what kind of request this is.',
    ],
    example: 'A "perform function" command is type 8, subtype 1 — (8,1).',
    ref: 'ICD §3.3.3.2.1 (ccf).',
  },
  apid: APID,
  critical: {
    title: 'Critical (hazardous) command',
    body: [
      'Marking a command critical (CCF_CRITICAL = Y) makes the ground system '
      + 'require an explicit second confirmation ("arming") from the operator '
      + 'before it is released — protection against a mis-click.',
      'Use it for anything irreversible or potentially damaging: pyro '
      + 'firing, deployments, high-power switching, FDIR overrides.',
    ],
    ref: 'ICD §3.3.3.2.1 (CCF_CRITICAL).',
  },
  args: {
    title: 'Command arguments',
    body: [
      'Each row becomes a command parameter definition (cpc — the type and '
      + 'how operators enter it) plus a layout element (cdf — where it sits '
      + 'in the packet). Bit offsets are counted from the end of the packet '
      + 'header and computed automatically from the types; reorder with the '
      + 'arrows and watch the map below.',
      'Three kinds of element:\n'
      + '• Editable — the operator enters the value when preparing the '
      + 'command (e.g. a target mode). The "value" column is then an '
      + 'optional default.\n'
      + '• Fixed — a real parameter whose value is locked (visible to the '
      + 'operator but not changeable). Requires a value (or a parameter '
      + 'default).\n'
      + '• Fixed area — constant bits baked invisibly into the packet: '
      + 'function IDs, spares, magic numbers. Needs a bit length and a value.',
      'Parameter names are reusable: if two commands share an argument '
      + '(same name), it is defined once in cpc and laid out per command in '
      + 'cdf.',
      'Values entered here are raw (on-board) values. To let operators work '
      + 'in engineering units or named states instead, attach a TC '
      + 'calibration to the parameter afterwards (calibration wizard → alias '
      + 'set or de-calibration curve).',
    ],
    ref: 'ICD §3.3.3.2.2 (cpc), §3.3.3.2.3 (cdf), Appendix A (PTC/PFC).',
  },
  verification: {
    title: 'Command verification (PUS service 1)',
    body: [
      'When the ground releases a command, the on-board software can answer '
      + 'with service-1 reports confirming each step: acceptance (1,1/1,2), '
      + 'start (1,3/1,4) and completion (1,7/1,8). The operator sees the '
      + 'command turn green stage by stage — or red with a failure report.',
      'Your selection here does two things:\n'
      + '• sets the acknowledgement flags (CCF_ACK) that ask the on-board '
      + 'software to send those reports (acceptance = 1, start = 2, '
      + 'completion = 8; e.g. acceptance + completion = 9)\n'
      + '• links the matching verification stages (cvs/cvp) so the ground '
      + 'actually waits for them, with a timeout window.',
      'Only request stages your on-board software really implements — '
      + 'otherwise every command ends in a verification timeout. If your '
      + 'unit has no service 1 at all, untick everything; you can still '
      + 'verify via telemetry values later (cve table).',
    ],
    ref: 'ECSS-E-ST-70-41 service 1; ICD §3.3.3.4 (cvs/cve/cvp), CCF_ACK.',
  },
}
