"""PUS service catalog (ECSS-E-ST-70-41C, 'PUS-C'; types also valid for PUS-A).

Used by the UI to explain service types/subtypes and to pre-fill packet and
command definitions. Only the services relevant for a typical instrument /
unit team are listed; type and subtype stay freely editable everywhere.
"""

from __future__ import annotations

PUS_SERVICES: list[dict] = [
    {
        "service": 1, "name": "Request verification",
        "help": "Reports generated by the on-board software to confirm (or fail) "
                "each step of a telecommand's life: acceptance, start, progress, "
                "completion. You normally do not define these packets yourself — "
                "the platform/OBSW provides them — but your commands' verification "
                "settings (cvs/cve/cvp tables and CCF_ACK) rely on them.",
        "tm": [{"subtype": 1, "name": "Acceptance success"},
               {"subtype": 2, "name": "Acceptance failure"},
               {"subtype": 3, "name": "Start success"},
               {"subtype": 4, "name": "Start failure"},
               {"subtype": 5, "name": "Progress success"},
               {"subtype": 6, "name": "Progress failure"},
               {"subtype": 7, "name": "Completion success"},
               {"subtype": 8, "name": "Completion failure"}],
        "tc": [],
    },
    {
        "service": 3, "name": "Housekeeping",
        "help": "Periodic reports of your unit's health and status parameters. "
                "This is usually the bulk of an instrument MIB: each housekeeping "
                "report is one TM packet identified by its Structure ID (SID), "
                "carried as the first field of the packet body.",
        "tm": [{"subtype": 25, "name": "Housekeeping parameter report",
                "note": "The standard periodic HK packet. PI1 = SID."},
               {"subtype": 26, "name": "Diagnostic parameter report"}],
        "tc": [{"subtype": 5, "name": "Enable periodic housekeeping reports"},
               {"subtype": 6, "name": "Disable periodic housekeeping reports"},
               {"subtype": 31, "name": "Modify collection interval"}],
    },
    {
        "service": 5, "name": "Event reporting",
        "help": "Asynchronous notifications from your unit: anomalies, mode "
                "changes, completed activities. Each event packet carries an "
                "Event ID (RID/EID), typically as PI1.",
        "tm": [{"subtype": 1, "name": "Informative event"},
               {"subtype": 2, "name": "Low-severity anomaly"},
               {"subtype": 3, "name": "Medium-severity anomaly"},
               {"subtype": 4, "name": "High-severity anomaly"}],
        "tc": [{"subtype": 5, "name": "Enable event report generation"},
               {"subtype": 6, "name": "Disable event report generation"}],
    },
    {
        "service": 6, "name": "Memory management",
        "help": "Load, dump and check on-board memory. Relevant if your unit "
                "supports software patching or table uploads.",
        "tm": [{"subtype": 6, "name": "Memory dump report"},
               {"subtype": 10, "name": "Memory check report"}],
        "tc": [{"subtype": 2, "name": "Load memory (absolute addresses)"},
               {"subtype": 5, "name": "Dump memory"},
               {"subtype": 9, "name": "Check memory"}],
    },
    {
        "service": 8, "name": "Function management",
        "help": "The workhorse for unit-specific commands: 'perform function X "
                "with arguments Y'. The Function ID is the first parameter of "
                "the command; your own arguments follow.",
        "tm": [],
        "tc": [{"subtype": 1, "name": "Perform function",
                "note": "Most instrument commands are (8,1) with a Function ID."}],
    },
    {
        "service": 9, "name": "Time management",
        "help": "Time distribution and rate control. Usually platform-level; "
                "rarely defined by unit teams.",
        "tm": [], "tc": [],
    },
    {
        "service": 11, "name": "Time-based scheduling",
        "help": "On-board command schedule (time-tagged commands). Handled by "
                "the platform; your commands can be inserted into the schedule.",
        "tm": [], "tc": [{"subtype": 4, "name": "Insert activities into schedule"}],
    },
    {
        "service": 12, "name": "On-board monitoring",
        "help": "On-board limit checking of parameters. Define if your unit "
                "performs autonomous monitoring with configurable limits.",
        "tm": [{"subtype": 12, "name": "Check transition report"}],
        "tc": [{"subtype": 1, "name": "Enable parameter monitoring"},
               {"subtype": 2, "name": "Disable parameter monitoring"}],
    },
    {
        "service": 13, "name": "Large packet transfer",
        "help": "Splits data too large for one packet into parts (e.g. science "
                "data products, images).",
        "tm": [{"subtype": 1, "name": "First downlink part"},
               {"subtype": 2, "name": "Intermediate downlink part"},
               {"subtype": 3, "name": "Last downlink part"}],
        "tc": [],
    },
    {
        "service": 15, "name": "On-board storage and retrieval",
        "help": "Packet stores on the platform's mass memory. Usually platform-"
                "level configuration.",
        "tm": [], "tc": [],
    },
    {
        "service": 17, "name": "Test ('are you alive')",
        "help": "Connection test: ground sends (17,1), your unit answers with "
                "(17,2). Cheap to implement and very useful during EGSE testing — "
                "define both packets early.",
        "tm": [{"subtype": 2, "name": "Are-you-alive connection report"}],
        "tc": [{"subtype": 1, "name": "Are-you-alive connection test"}],
    },
    {
        "service": 20, "name": "On-board parameter management",
        "help": "Read and set individual on-board parameters by Parameter ID. "
                "If supported, your TM parameters' on-board IDs go into PCF_PID.",
        "tm": [{"subtype": 2, "name": "Parameter value report"}],
        "tc": [{"subtype": 1, "name": "Report parameter values"},
               {"subtype": 3, "name": "Set parameter values"}],
    },
]


def pus_services_json() -> list[dict]:
    return PUS_SERVICES
